name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]  # Cambia a "master" si usas esa rama

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public/'  # Asegúrate que esta carpeta existe

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
